[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[template.environment]
  STATUSKIT_PAGE_TITLE = "MWE Enterprise Cloud"
  STATUSKIT_COMPANY_LOGO = "https://www.medicalwebexperts.com/images/cube.a058a0612b0b23a8.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "https://www.medicalwebexperts.com/#contact-us"
  STATUSKIT_RESOURCES_LINK = "https://www.medicalwebexperts.com/"
